# migrations/alembic/versions/2bf1f3cb2f9a_initial_schema.py
"""initial schema

Revision ID: 2bf1f3cb2f9a
Revises: 
Create Date: 2025-08-04 20:04:34.806673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf1f3cb2f9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('tfa_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('ccu_minutely',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('ccu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ts')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_logins',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('code_try', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_try', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('admin_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('price_uah', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_plain', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=60), nullable=False),
    sa.Column('allowed_sessions', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['code_batches.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_plain')
    )
    op.create_index('ix_access_codes_event_active', 'access_codes', ['event_id', 'revoked'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('amount_uah', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refund_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('token_jti', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('watch_seconds', sa.Integer(), nullable=False),
    sa.Column('bytes_out', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('orders')
    op.drop_index('ix_access_codes_event_active', table_name='access_codes')
    op.drop_table('access_codes')
    op.drop_table('code_batches')
    op.drop_table('admin_audit')
    op.drop_table('failed_logins')
    op.drop_table('events')
    op.drop_table('ccu_minutely')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
