# migrations/alembic/versions/d6300456d77a_add_bunny_video_path_to_events.py
"""Add bunny_video_path to events

Revision ID: d6300456d77a
Revises: a07b5d543e49
Create Date: 2025-12-27 08:30:06.075773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6300456d77a'
down_revision: Union[str, Sequence[str], None] = 'a07b5d543e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_codes', 'max_concurrent_sessions')
    op.drop_column('access_codes', 'cooldown_seconds')
    op.alter_column('admin_audit', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ccu_minutely', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_code_allowed_events_code'), table_name='code_allowed_events')
    op.drop_index(op.f('ix_code_allowed_events_event'), table_name='code_allowed_events')
    op.alter_column('code_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('events', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.alter_column('failed_logins', 'last_try',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('orders', 'refund_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_events', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('session_events', 'at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_events', 'details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_sessions_event_id_events'), 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'last_seen_at')
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'device_fingerprint')
    op.drop_column('sessions', 'refresh_expires_at')
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('refresh_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('device_fingerprint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_sessions_event_id_events'), 'sessions', 'events', ['event_id'], ['id'])
    op.alter_column('session_events', 'details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('session_events', 'at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_events', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('orders', 'refund_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('failed_logins', 'last_try',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.alter_column('events', 'ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'starts_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('code_batches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_code_allowed_events_event'), 'code_allowed_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_code_allowed_events_code'), 'code_allowed_events', ['code_id'], unique=False)
    op.alter_column('ccu_minutely', 'ts',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('admin_audit', 'ts',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('access_codes', sa.Column('cooldown_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('access_codes', sa.Column('max_concurrent_sessions', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
