# migrations/alembic/versions/e9ee9aa6fe73_add_bunny_video_path_and_mux_env_key_to_.py
"""Add bunny_video_path and mux_env_key to events

Revision ID: e9ee9aa6fe73
Revises: d6300456d77a
Create Date: 2025-12-27 09:14:03.604601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ee9aa6fe73'
down_revision: Union[str, Sequence[str], None] = 'd6300456d77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('bunny_video_path', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('mux_env_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'mux_env_key')
    op.drop_column('events', 'bunny_video_path')
    # ### end Alembic commands ###
